# Generated by Django 5.2 on 2025-05-30 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_sensors_sensor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ambients',
            new_name='Ambient',
        ),
    ]
