# Generated by Django 5.2 on 2025-05-30 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_ambient_descricao_alter_ambient_ni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambient',
            name='ni',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='O NI deve ser no formato SN seguido de 4 dígitos ou apenas 7 dígitos.', regex='^(SN\\d{4}|\\d{7})$')]),
        ),
    ]
