# Generated by Django 5.2 on 2025-05-30 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_ambient_ni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='mac_address',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Formato de endereço MAC inválido. Exemplo: 00:1A:2B:3C:4D:5E', regex='^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$')]),
        ),
    ]
