# Generated by Django 5.2 on 2025-06-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_sensor_mac_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor',
            field=models.CharField(max_length=100),
        ),
    ]
