# Generated by Django 5.2 on 2025-06-03 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_sensorhumidity_sensorluminosity_sensortemperature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambient',
            name='ni',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='O NI deve ser no formato SNXXXXX ou XXXXXXX (onde X é um dígito).', regex='^(SN\\d{5}|\\d{7})$')]),
        ),
        migrations.AlterField(
            model_name='ambient',
            name='sig',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(message='O SIG deve conter exatamente 8 números.', regex='^[0-9]{8}$')]),
        ),
    ]
