# Generated by Django 5.2 on 2025-06-05 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_sensor_rename_object_id_historic_ambient_object_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SensorCounter',
        ),
        migrations.DeleteModel(
            name='SensorHumidity',
        ),
        migrations.DeleteModel(
            name='SensorLuminosity',
        ),
        migrations.DeleteModel(
            name='SensorTemperature',
        ),
    ]
