# Generated by Django 5.2 on 2025-06-13 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_sensor_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='tipo',
        ),
    ]
