# Generated by Django 5.2 on 2025-06-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_sensor_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='unidade_medida',
            field=models.CharField(choices=[('%', '%'), ('uni', 'uni'), ('ºC', 'ºC'), ('lux', 'lux')], max_length=10),
        ),
    ]
